# Generated by Django 4.0 on 2022-12-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans3',
        ),
    ]
